curl -H "Content-Type: application/json" -d '{"firstName":"Jack","lastName":"Smith", "education": "professional", "isEducator": true, "programTrack": "mentor", "province": "Ontario", "gender": "male", "isIndigenous": true, "comments": "Has won olympic math awards."}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Rosey","lastName":"Johnson", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 11, "fieldOfStudy": "music", "province": "Ontario", "gender": "female", "isIndigenous": true, "comments": "Is looking for someone to tutor her."}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Hunter","lastName":"Locker", "education": "postsecondary", "programTrack": "both", "gender": "male", "province": "Ontario", "isIndigenous": false}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Jose","lastName":"Pilapil", "education": "professional", "isEducator": true "programTrack": "mentor", "grade": 11, "fieldOfStudy": "IT", "province": "Ontario", "gender": "male", "isIndigenous": true, "comments": "can mentor"}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Amit","lastName":"Agrawal", "education": "highschool", "isEducator": true "programTrack": "mentee", "grade": 10, "fieldOfStudy": "IT", "province": "Ontario", "gender": "male", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Sonia","lastName":"Fraser", "education": "professional", "isEducator": false, "programTrack": "mentor", "grade": 9, "fieldOfStudy": "French Language", "province": "Quebec", "gender": "female", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Jill","lastName":"Simpson", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 9, "fieldOfStudy": "French Language", "province": "Quebec", "gender": "female", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Dominic","lastName":"Baker", "education": "professional", "isEducator": false, "programTrack": "mentor", "grade": 11, "fieldOfStudy": "Medicine", "province": "Ontario", "gender": "male", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Eric","lastName":"Butler", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 10, "fieldOfStudy": "Medicine", "province": "New Brunswick", "gender": "male", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Lillian","lastName":"Knox", "education": "professional", "isEducator": false, "programTrack": "mentor", "grade": 10, "fieldOfStudy": "Media", "province": "New Brunswick", "gender": "female", "isIndigenous": false "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Tracey","lastName":"Jones", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 10, "fieldOfStudy": "Media", "province": "New Brunswick", "gender": "male", "isIndigenous": false "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Stephanie","lastName":"Gill", "education": "professional", "isEducator": false, "programTrack": "mentor", "grade": 10, "fieldOfStudy": "History", "province": "New Brunswick", "gender": "male", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Alexandra","lastName":"Martin", "education": "highschool", "isEducator": false, "programTrack": "mentor", "grade": 10, "fieldOfStudy": "History", "province": "New Brunswick", "gender": "male", "isIndigenous": true, "comments": ""}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Austin","lastName":"Mitchell", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 10, "fieldOfStudy": null, "province": "Ontario", "gender": "male", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Joan","lastName":"Glover", "education": "postsecondary", "isEducator": false, "programTrack": "mentee", "grade": 12, "fieldOfStudy": null, "province": "Quebec", "gender": "female", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Charles","lastName":"Parr", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "Mathematics", "province": "Ontario", "gender": "male", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Jennifer","lastName":"Allan", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "French", "province": "Quebec", "gender": "female", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Nathan","lastName":"Berry", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "Physics", "province": "New Brunswick", "gender": "male", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Rachel","lastName":"Walsh", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "French", "province": "Newfoundland and Labrador", "gender": "female", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Cameron","lastName":"May", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 9, "fieldOfStudy": "French", "province": "Quebec", "gender": "female", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Heather","lastName":"Watson", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 11, "fieldOfStudy": "Science", "province": "Ontario", "gender": "female", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Amy","lastName":"Payne", "education": "postsecondary", "isEducator": false, "programTrack": "mentee", "grade": 11, "fieldOfStudy": "Computer science", "province": "Alberta", "gender": "female", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Colin","lastName":"McDonald", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "Computer science", "province": "Alberta", "gender": "male", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Zoe","lastName":"Nash", "education": "professional", "isEducator": true, "programTrack": "mentor", "grade": null, "fieldOfStudy": "Programming", "province": "Nova Scotia", "gender": "female", "isIndigenous": true, "comments": null}' http://localhost:8080/registernewcustomer
curl -H "Content-Type: application/json" -d '{"firstName":"Jasmine","lastName":"Wilkins", "education": "highschool", "isEducator": false, "programTrack": "mentee", "grade": 12, "fieldOfStudy": "Programming", "province": "Nova Scotia", "gender": "female", "isIndigenous": false, "comments": null}' http://localhost:8080/registernewcustomer